### ISSUE TITLE
iOS 11 IBSS fail

### ISSUE THREAD

**Issue by frankl1m** [haiyuidesu/iBoot64Patcher#1]
iOS 11.4.1
iPhone 5S  BoardID N51AP

Patching IBSS 

Both line tried:
iBoot64Patcher -p ibss.raw ibss.pwn -e
iBoot64Patcher -p ibss.raw ibss.pwn 

[main]: starting...
[main]: detected iBoot-4076.70.15!
[main]: base_addr = 0x180380000
[main]: applying generic iBoot patches...
[apply_generic_patches]: unable to detect any kernel load routine.

kairos tested too device boots but not partitions
boot args for kairos and iBoot64Patcher rd=md0 -v
Not succes on iOS 12

**Comment by haiyuidesu** [comment]
Hello, N69AP is corresponding to an iPhoneSE (iPhone8,4), are you sure you correctly decrypted it?

**Comment by frankl1m** [comment]
My mistake is N51AP iPhone 5S, i used kairos to decrypt de cipher the iBEC and IBSS, keys getted from theiphonewiki is ok that part, iBoot64Patcher fails on patch raw ibec and ibss, i am trying differents tools with kairos i think the most complete but is failing on ios 12, device never mount partition so is not patching ok, but with this tool iBoot64patch even it dont detect where to patch

**Comment by haiyuidesu** [comment]
I just tried with an N69uAP (N69AP's one are unavailable, see: [there](https://www.theiphonewiki.com/wiki/Gebze_15G77_(iPhone8,4))) and iBoot64Patcher did had a problem, I'll push a fix and wait for a return.

**Comment by frankl1m** [comment]
I putted internal model incorrectly it was fixed, is N51AP iPhone 5S [https://www.theiphonewiki.com/wiki/Gebze_15G77_(iPhone6,1)]

**Comment by haiyuidesu** [comment]
I've just pushed an update to iBoot64Patcher, please try again.

**Comment by frankl1m** [comment]
Now after pwn with ipwnder_lite from dora_ios, with these latest patch after pass IBSS and IBEC it boots direct dont go to recovery

**Comment by frankl1m** [comment]
iBSS
[main]: starting...
[main]: detected iBoot-4076.70.15!
[main]: base_addr = 0x180380000
[main]: applying generic iBoot patches...

[rmv_signature_check]: removing signatures checks...
[rmv_signature_check]: found '_image4_validate_property_cb_interposer' beginning!
[rmv_signature_check]: patched to MOV x0, #0 insn = 0x18038b8b4
[rmv_signature_check]: patched to RET insn = 0x18038b8b8
[rmv_signature_check]: successfully removed signatures checks!



iBec
[main]: starting...
[main]: detected iBoot-4076.70.15!
[main]: base_addr = 0x830000000
[main]: applying generic iBoot patches...

[rmv_signature_check]: removing signatures checks...
[rmv_signature_check]: found '_image4_validate_property_cb_interposer' beginning!
[rmv_signature_check]: patched to MOV x0, #0 insn = 0x83000a068
[rmv_signature_check]: patched to RET insn = 0x83000a06c
[rmv_signature_check]: successfully removed signatures checks!

[enable_kernel_debug]: enabling kernel debugging...
[enable_kernel_debug]: found the BL to '_security_allow_modes' function
[enable_kernel_debug]: patched to MOVZ x0, #1 insn = 0x83000bfa4
[enable_kernel_debug]: successfully enabled kernel debugging!

[set_custom_bootargs]: setting "rd=md0 -v" boot-args...
[set_custom_bootargs]: found boot-args string = 0x83000d3b0
[set_custom_bootargs]: patched the ADR instruction = 0x83000d3b0
[set_custom_bootargs]: moved from CSEL instruction (0x83000d3bc) to MOV x27, x9
[set_custom_bootargs]: found the CBZ instruction = 0x83000d3a0
[set_custom_bootargs]: replaced the ADR instruction pointing address = 0x83000d434
[set_custom_bootargs]: successfully set new bootargs!

[allow_any_imagetype]: allowing to load any type of images...
[allow_any_imagetype]: successfully allowed to load any image types!

[prevent_kaslr_slide]: patching the kaslr slide...
[prevent_kaslr_slide]: found the 'load_kernelcache()' function!
[prevent_kaslr_slide]: patched 'slide_phys' to MOV x9, #0x0 = 0x83000d22c
[prevent_kaslr_slide]: patched 'slide_virt' to MOV x22, x9 = 0x83000d23c
[prevent_kaslr_slide]: NOPed all other instructions.
[prevent_kaslr_slide]: successfully patched the kaslr slide!

**Comment by haiyuidesu** [comment]
Just to be sure, after patching it, you repacked everything and created an IMG4 right-?

**Comment by frankl1m** [comment]
Command line ios 11.4.1 iPhone6,1
../bin/iBoot64Patcher -p ibss.raw ibss.pwn -b \"rd=md0 -v\"
../bin/iBoot64Patcher -p ibec.raw ibec.pwn -b \"rd=md0 -v\"

**Comment by haiyuidesu** [comment]
That was not my question... did you created an IMG4 after the creation of the patched iBoots?

**Comment by frankl1m** [comment]
Yes correct i always do i unpack with img4 + iv + key and pack again with ticket, is my first time working with ios 12, with ios 13-14 i tested successfully with kairos, but even kairos break the SEP on iOS 12 or iBoot64patcher are not able to work yet. Kairos boots ok with custom ramdisk but not SEP

**Comment by haiyuidesu** [comment]
Well, I have no idea where the problem could be so I apologize.

To be honest the few times I tried to boot an N51AP, everything's worked fine (but it was on iOS 12) and here's how I proceeded (example with an iBEC):

```
$ img4 -i ibec.im4p ibec.raw -k [iv][key]
$ iBoot64Patcher -p ibec.raw ibec.pwn -e
$ img4tool -c ibec.im4p -t ibec -d ibec ibec.pwn
$ img4tool -p ibec.im4p -c ibec.img4
$ iPwnder32 -p
$ recovery -f ibec.img4
```

Everything's worked fine with iBoot64Patcher so I can't tell why it is not working for you.

**Comment by haiyuidesu** [comment]
Well, the main issue has been fixed so I'm closing it.

**Comment by frankl1m** [comment]
Issue is not fixed check details

Tested:
iOS 11.4.1 dont go to recovery for flash other files
IOS 12.5.5 same that 11.4.1
iBSS + IBEC flash OK, after send command to go recovery device boots normally instead of go to recovery for flash other partitions

Kairos have other problem i can flash all except Trustcache and device boots good, but parittions cannot be mounted i think problem of SEP

If i flash trustcache i got kernel panic after boot

**Comment by frankl1m** [comment]
Using this utility can confirm iOS 14 working good, issue is on iOS 11-12 IBSS + IBEC  working good with SEP

**Comment by frankl1m** [comment]
Problem is on iBEC sure, i tested IBSS maked with iBoot64Patcher+ IBEC with kairos appears to be good at least boots without SEP, and iBec from kairos + iBSS from iBoot64Patcher dont work same boots after flash iBec just on ios 11-12

Cannot flash trust cache message on verbose "Only one static trust cache allowed"

**Comment by haiyuidesu** [comment]
The issue IS fixed since the main request was that iBoot64Patcher did not apply any patches and failed (which was fixed).

Your issue now is another thing which I can't answer since I don't own any devices running iOS 11.4.1 (or any devices under my hand right now).

However, iBoot64Patcher is applying the same patches at the same addresses as Kairos, maybe you should retry without applying my extra patches (I saw you did it so-)?
